//! WebAssembly surface of the Cabal engine.
//!
//! Everything crossing the boundary is a string-keyed, MILA-shaped value
//! (`"A PAR"`, `"F STP/NC"`, `"S1901M"`, `"FRANCE"`), so the same JSON works for
//! the browser, the Durable Object, saved games and AI harnesses. TypeScript
//! types for every value are generated by `tsify` into the wasm-pack output.

use std::collections::HashMap;

use cabal_engine::geo::{Map, SupplyCenter, Terrain, UnitKind};
use cabal_engine::json::{MilaState, SavedGame, state_from_mila, state_to_mila};
use cabal_engine::order::AnyOrder;
use cabal_engine::outcome::{AdjustOutcome, RetreatOutcome};
use cabal_engine::parse::parse;
use cabal_engine::rulebook::Rulebook;
use cabal_engine::state::PhaseKind;
use cabal_engine::text::{
    adjust_text, describe_outcome, order_text, outcome_code, retreat_text, unit_text,
};
use cabal_engine::{Game as EngineGame, PhaseResult, Status};
use serde::{Deserialize, Serialize};
use tsify::{Ts, Tsify};
use wasm_bindgen::prelude::*;

/// Engine version string, useful as a smoke test that the module loaded.
#[wasm_bindgen]
pub fn version() -> String {
    cabal_engine::VERSION.to_string()
}

// ---------- map ----------

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
#[tsify(hashmap_as_object, missing_as_null)]
pub struct ProvinceInfo {
    /// Upper case three letter code (`STP`).
    pub id: String,
    pub name: String,
    /// `land`, `coast` or `sea`.
    pub terrain: String,
    /// `null`, `"neutral"` or a power code (`"RUS"`).
    pub supply_center: Option<String>,
    /// Named coasts (`["NC", "SC"]`), empty otherwise.
    pub coasts: Vec<String>,
    /// Provinces an army may move to directly.
    pub army_adjacent: Vec<String>,
    /// Regions a fleet may move to, keyed by the coast it starts from (`""` for none).
    pub fleet_adjacent: HashMap<String, Vec<String>>,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
pub struct PowerInfo {
    pub code: String,
    pub name: String,
    pub homes: Vec<String>,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
#[tsify(hashmap_as_object, missing_as_null)]
pub struct MapInfo {
    pub name: String,
    pub powers: Vec<PowerInfo>,
    pub provinces: Vec<ProvinceInfo>,
}

fn terrain_name(t: Terrain) -> &'static str {
    match t {
        Terrain::Land => "land",
        Terrain::Coast => "coast",
        Terrain::Sea => "sea",
    }
}

/// Static description of the standard map.
#[wasm_bindgen]
pub fn map_info() -> Result<Ts<MapInfo>, JsError> {
    let map = Map::standard();
    let powers = map
        .power_ids()
        .map(|p| PowerInfo {
            code: map.power(p).code.clone(),
            name: map.power(p).name.clone(),
            homes: map
                .homes(p)
                .iter()
                .map(|&h| map.province(h).name.to_ascii_uppercase())
                .collect(),
        })
        .collect();
    let provinces = map
        .province_ids()
        .map(|p| {
            let prov = map.province(p);
            let mut fleet_adjacent = HashMap::new();
            for r in map.regions_of(p) {
                let key = r.coast.map(|c| c.code().to_string()).unwrap_or_default();
                let mut dests: Vec<String> = map
                    .reachable(r, UnitKind::Fleet)
                    .map(|d| map.region_name(d))
                    .collect();
                dests.sort();
                if !dests.is_empty() || r.coast.is_none() {
                    fleet_adjacent.insert(key, dests);
                }
            }
            let mut army_adjacent: Vec<String> = map
                .reachable(cabal_engine::Region::land(p), UnitKind::Army)
                .map(|d| map.province(d.province).name.to_ascii_uppercase())
                .collect();
            army_adjacent.sort();
            army_adjacent.dedup();
            ProvinceInfo {
                id: prov.name.to_ascii_uppercase(),
                name: prov.full_name.clone(),
                terrain: terrain_name(prov.terrain).to_string(),
                supply_center: match prov.supply_center {
                    SupplyCenter::None => None,
                    SupplyCenter::Neutral => Some("neutral".to_string()),
                    SupplyCenter::Home(pw) => Some(map.power(pw).code.clone()),
                },
                coasts: prov.coasts.iter().map(|c| c.code().to_string()).collect(),
                army_adjacent,
                fleet_adjacent,
            }
        })
        .collect();
    Ok(MapInfo {
        name: map.name.clone(),
        powers,
        provinces,
    }
    .into_ts()?)
}

// ---------- state ----------

/// Board state in MILA layout. Power names are full upper case (`FRANCE`).
#[derive(Tsify, Serialize, Deserialize, Clone, Debug, Default)]
#[tsify(hashmap_as_object)]
pub struct State {
    /// Phase name such as `S1901M`, or `COMPLETED`.
    pub name: String,
    pub units: HashMap<String, Vec<String>>,
    pub centers: HashMap<String, Vec<String>>,
    pub homes: HashMap<String, Vec<String>>,
    /// Retreat phase only: legal retreat destinations per dislodged unit.
    pub retreats: HashMap<String, HashMap<String, Vec<String>>>,
    /// Adjustment phase only: build allowance and buildable home centres.
    pub builds: HashMap<String, BuildInfo>,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug, Default)]
pub struct BuildInfo {
    pub count: i32,
    pub homes: Vec<String>,
}

impl From<MilaState> for State {
    fn from(m: MilaState) -> Self {
        State {
            name: m.name,
            units: m.units.into_iter().collect(),
            centers: m.centers.into_iter().collect(),
            homes: m.homes.into_iter().collect(),
            retreats: m
                .retreats
                .into_iter()
                .map(|(k, v)| (k, v.into_iter().collect()))
                .collect(),
            builds: m
                .builds
                .into_iter()
                .map(|(k, v)| {
                    (
                        k,
                        BuildInfo {
                            count: v.count,
                            homes: v.homes,
                        },
                    )
                })
                .collect(),
        }
    }
}

impl From<State> for MilaState {
    fn from(s: State) -> Self {
        MilaState {
            name: s.name,
            units: s.units.into_iter().collect(),
            centers: s.centers.into_iter().collect(),
            homes: s.homes.into_iter().collect(),
            retreats: s
                .retreats
                .into_iter()
                .map(|(k, v)| (k, v.into_iter().collect()))
                .collect(),
            builds: s
                .builds
                .into_iter()
                .map(|(k, v)| {
                    (
                        k,
                        cabal_engine::json::BuildInfo {
                            count: v.count,
                            homes: v.homes,
                        },
                    )
                })
                .collect(),
        }
    }
}

/// Orders per power in MILA text, e.g. `{ "FRANCE": ["A PAR - BUR"] }`.
#[derive(Tsify, Serialize, Deserialize, Clone, Debug, Default)]
#[tsify(hashmap_as_object)]
pub struct OrdersByPower {
    pub orders: HashMap<String, Vec<String>>,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
pub struct OrderResult {
    pub power: String,
    /// `A PAR`
    pub unit: String,
    /// Canonical order text as adjudicated (illegal orders appear as holds).
    pub order: String,
    pub ok: bool,
    /// `ok`, `bounce`, `cut`, `void`, `dislodged`, `no_path`, `illegal`, `paradox`, `disband`.
    pub code: String,
    /// Human readable reason.
    pub reason: String,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
pub struct DislodgedInfo {
    pub unit: String,
    pub attacker_from: String,
    pub retreat_options: Vec<String>,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug)]
#[tsify(hashmap_as_object, missing_as_null)]
pub struct PhaseOutcome {
    /// The phase that was adjudicated.
    pub phase: String,
    pub results: Vec<OrderResult>,
    pub dislodged: Vec<DislodgedInfo>,
    pub standoffs: Vec<String>,
    /// Units removed by the civil disorder rule (adjustment phases).
    pub civil_disorder: Vec<String>,
    /// State after the phase, named with the next phase.
    pub next: State,
    /// `active`, `solo:<POWER>` or `draw`.
    pub status: String,
}

#[derive(Tsify, Serialize, Deserialize, Clone, Debug, Default)]
#[tsify(hashmap_as_object)]
pub struct LegalOrders {
    /// Legal orders per unit (`"A PAR": ["A PAR H", "A PAR - BUR", ...]`).
    pub by_unit: HashMap<String, Vec<String>>,
    /// Adjustment phases: units to build (positive) or remove (negative).
    pub allowance: i32,
}

fn status_text(map: &Map, s: Status) -> String {
    match s {
        Status::Active => "active".into(),
        Status::Solo { winner } => format!("solo:{}", map.power(winner).name.to_ascii_uppercase()),
        Status::Draw => "draw".into(),
    }
}

fn rulebook_of(name: Option<String>) -> Result<Rulebook, JsError> {
    match name {
        None => Ok(Rulebook::default()),
        Some(n) => {
            Rulebook::by_name(&n).ok_or_else(|| JsError::new(&format!("unknown rulebook {n}")))
        }
    }
}

fn typed_orders(game: &EngineGame, orders: &OrdersByPower) -> Result<Vec<AnyOrder>, JsError> {
    let map = game.map();
    let mut out = Vec::new();
    for (power, list) in &orders.orders {
        let p = map
            .find_power(power)
            .ok_or_else(|| JsError::new(&format!("unknown power {power}")))?;
        for text in list {
            let parsed = parse(map, text).map_err(|e| JsError::new(&format!("{text}: {e}")))?;
            let order = match game.phase().kind {
                PhaseKind::Movement => parsed.to_movement(Some(p)).map(AnyOrder::Movement),
                PhaseKind::Retreat => parsed.to_retreat(Some(p)).map(AnyOrder::Retreat),
                PhaseKind::Adjustment => parsed.to_adjustment(Some(p)).map(AnyOrder::Adjustment),
            }
            .map_err(|e| JsError::new(&format!("{text}: {e}")))?;
            out.push(order);
        }
    }
    Ok(out)
}

fn outcome_of(game: &EngineGame, record: &cabal_engine::PhaseRecord) -> PhaseOutcome {
    let map = game.map();
    let pos = &record.state.position;
    let power_name = |p: cabal_engine::Power| map.power(p).name.to_ascii_uppercase();
    let mut results = Vec::new();
    let mut dislodged = Vec::new();
    let mut standoffs = Vec::new();
    let mut civil_disorder = Vec::new();
    match &record.result {
        PhaseResult::Movement(r) => {
            for (o, out) in r.orders.iter().zip(&r.outcomes) {
                let unit = pos
                    .unit_at(o.unit)
                    .map(|u| unit_text(map, u))
                    .unwrap_or_default();
                results.push(OrderResult {
                    power: power_name(o.power),
                    unit,
                    order: order_text(map, pos, o),
                    ok: out.succeeds(),
                    code: outcome_code(out).to_string(),
                    reason: describe_outcome(map, out),
                });
            }
            // retreat options come from the state after the phase
            for d in &r.dislodged {
                let options = cabal_engine::legal::legal_retreats(
                    map,
                    &game_state_after(game, record),
                    d.unit.power,
                )
                .remove(&d.unit.province())
                .unwrap_or_default()
                .into_iter()
                .filter_map(|o| match o.command {
                    cabal_engine::RetreatCommand::Retreat { dest, coast } => {
                        Some(map.region_name(cabal_engine::Region::new(dest, coast)))
                    }
                    _ => None,
                })
                .collect();
                dislodged.push(DislodgedInfo {
                    unit: unit_text(map, &d.unit),
                    attacker_from: map.province(d.attacker_from).name.to_ascii_uppercase(),
                    retreat_options: options,
                });
            }
            standoffs = r
                .standoffs
                .iter()
                .map(|&p| map.province(p).name.to_ascii_uppercase())
                .collect();
        }
        PhaseResult::Retreat(r) => {
            for (o, out) in r.orders.iter().zip(&r.outcomes) {
                let unit = record
                    .state
                    .dislodged
                    .iter()
                    .find(|d| d.unit.province() == o.unit)
                    .map(|d| unit_text(map, &d.unit))
                    .unwrap_or_default();
                let (ok, code, reason) = match out {
                    RetreatOutcome::Succeeds => (true, "ok", "retreats".to_string()),
                    RetreatOutcome::Bounced { with } => (
                        false,
                        "bounce",
                        format!(
                            "bounced with {}",
                            with.iter()
                                .map(|&p| map.province(p).name.to_ascii_uppercase())
                                .collect::<Vec<_>>()
                                .join(", ")
                        ),
                    ),
                    RetreatOutcome::Illegal { reason } => (
                        false,
                        "illegal",
                        format!("illegal retreat ({reason:?}), disbanded"),
                    ),
                    RetreatOutcome::Disbanded => (false, "disband", "disbanded".to_string()),
                };
                results.push(OrderResult {
                    power: power_name(o.power),
                    unit,
                    order: retreat_text(map, pos, o),
                    ok,
                    code: code.to_string(),
                    reason,
                });
            }
        }
        PhaseResult::Adjustment(r) => {
            for (o, out) in r.orders.iter().zip(&r.outcomes) {
                let (ok, code, reason) = match out {
                    AdjustOutcome::Succeeds => (true, "ok", "done".to_string()),
                    AdjustOutcome::Illegal { reason } => {
                        (false, "illegal", format!("illegal ({reason:?})"))
                    }
                };
                results.push(OrderResult {
                    power: power_name(o.power),
                    unit: String::new(),
                    order: adjust_text(map, pos, o),
                    ok,
                    code: code.to_string(),
                    reason,
                });
            }
            civil_disorder = r.civil_disorder.iter().map(|u| unit_text(map, u)).collect();
        }
    }
    PhaseOutcome {
        phase: record.state.phase.to_string(),
        results,
        dislodged,
        standoffs,
        civil_disorder,
        next: state_to_mila(map, &game.state).into(),
        status: status_text(map, game.status),
    }
}

/// The game state right after `record` (the current state when `record` is the last one).
fn game_state_after(
    game: &EngineGame,
    record: &cabal_engine::PhaseRecord,
) -> cabal_engine::GameState {
    let idx = game.history.iter().position(|r| std::ptr::eq(r, record));
    match idx {
        Some(i) if i + 1 < game.history.len() => game.history[i + 1].state.clone(),
        _ => game.state.clone(),
    }
}

// ---------- Game ----------

/// A game in progress. Holds the full phase history for replays and exports.
#[wasm_bindgen]
pub struct Game {
    inner: EngineGame,
}

#[wasm_bindgen]
impl Game {
    /// Start a new game on the standard map. `rulebook` is `2023` (default), `1982`, `1971` or `dptg`.
    #[wasm_bindgen(constructor)]
    pub fn new(rulebook: Option<String>) -> Result<Game, JsError> {
        Ok(Game {
            inner: EngineGame::new(Map::standard(), rulebook_of(rulebook)?),
        })
    }

    /// Resume from a state in MILA layout (no history).
    #[wasm_bindgen(js_name = fromState)]
    pub fn from_state(state: Ts<State>, rulebook: Option<String>) -> Result<Game, JsError> {
        let map = Map::standard();
        let s: State = state.to_rust()?;
        let gs =
            state_from_mila(map, &MilaState::from(s)).map_err(|e| JsError::new(&e.to_string()))?;
        Ok(Game {
            inner: EngineGame::from_state(map, rulebook_of(rulebook)?, gs),
        })
    }

    /// Replay a MILA saved game (JSON text) through the engine.
    #[wasm_bindgen(js_name = fromSaved)]
    pub fn from_saved(json: &str, rulebook: Option<String>) -> Result<Game, JsError> {
        let saved: SavedGame =
            serde_json::from_str(json).map_err(|e| JsError::new(&e.to_string()))?;
        let inner = EngineGame::from_saved(&saved, rulebook_of(rulebook)?)
            .map_err(|e| JsError::new(&e.to_string()))?;
        Ok(Game { inner })
    }

    pub fn phase(&self) -> String {
        if self.inner.is_finished() {
            "COMPLETED".to_string()
        } else {
            self.inner.phase().to_string()
        }
    }

    pub fn status(&self) -> String {
        status_text(self.inner.map(), self.inner.status)
    }

    #[wasm_bindgen(js_name = historyLength)]
    pub fn history_length(&self) -> usize {
        self.inner.history.len()
    }

    pub fn state(&self) -> Result<Ts<State>, JsError> {
        Ok(State::from(state_to_mila(self.inner.map(), &self.inner.state)).into_ts()?)
    }

    /// Legal orders for a power in the current phase.
    pub fn legal(&self, power: &str) -> Result<Ts<LegalOrders>, JsError> {
        let map = self.inner.map();
        let p = map
            .find_power(power)
            .ok_or_else(|| JsError::new(&format!("unknown power {power}")))?;
        let pos = &self.inner.state.position;
        let mut by_unit: HashMap<String, Vec<String>> = HashMap::new();
        let mut allowance = 0;
        match self.inner.phase().kind {
            PhaseKind::Movement => {
                for (province, orders) in cabal_engine::legal::legal_movement(map, pos, p) {
                    let unit = pos
                        .unit_at(province)
                        .map(|u| unit_text(map, u))
                        .unwrap_or_default();
                    by_unit.insert(
                        unit,
                        orders.iter().map(|o| order_text(map, pos, o)).collect(),
                    );
                }
            }
            PhaseKind::Retreat => {
                for (province, orders) in
                    cabal_engine::legal::legal_retreats(map, &self.inner.state, p)
                {
                    let unit = self
                        .inner
                        .state
                        .dislodged
                        .iter()
                        .find(|d| d.unit.province() == province)
                        .map(|d| unit_text(map, &d.unit))
                        .unwrap_or_default();
                    by_unit.insert(
                        unit,
                        orders.iter().map(|o| retreat_text(map, pos, o)).collect(),
                    );
                }
            }
            PhaseKind::Adjustment => {
                let (delta, orders) =
                    cabal_engine::legal::legal_adjustments(map, pos, self.inner.rulebook, p);
                allowance = delta;
                by_unit.insert(
                    String::new(),
                    orders.iter().map(|o| adjust_text(map, pos, o)).collect(),
                );
            }
        }
        Ok(LegalOrders { by_unit, allowance }.into_ts()?)
    }

    /// Adjudicate the current phase with the given orders and advance.
    pub fn process(&mut self, orders: Ts<OrdersByPower>) -> Result<Ts<PhaseOutcome>, JsError> {
        let orders: OrdersByPower = orders.to_rust()?;
        let typed = typed_orders(&self.inner, &orders)?;
        self.inner
            .process(&typed)
            .map_err(|e| JsError::new(&e.to_string()))?;
        let record = self.inner.history.last().expect("phase recorded");
        Ok(outcome_of(&self.inner, record).into_ts()?)
    }

    /// Outcome of a past phase by index into the history.
    pub fn outcome(&self, index: usize) -> Result<Ts<PhaseOutcome>, JsError> {
        let record = self
            .inner
            .history
            .get(index)
            .ok_or_else(|| JsError::new("no such phase"))?;
        Ok(outcome_of(&self.inner, record).into_ts()?)
    }

    /// Export as MILA saved game JSON text.
    #[wasm_bindgen(js_name = toSaved)]
    pub fn to_saved(&self, id: &str) -> Result<String, JsError> {
        serde_json::to_string(&self.inner.to_saved(id)).map_err(|e| JsError::new(&e.to_string()))
    }

    /// End the game by agreement.
    #[wasm_bindgen(js_name = declareDraw)]
    pub fn declare_draw(&mut self) {
        self.inner.declare_draw();
    }
}

// ---------- stateless helpers ----------

/// Parse an order and return its canonical text, or throw. The unit kind must be given
/// in the text (`A PAR - BUR`), since no board is consulted.
#[wasm_bindgen(js_name = canonicalOrder)]
pub fn canonical_order(text: &str, phase_kind: &str, power: &str) -> Result<String, JsError> {
    let map = Map::standard();
    let p = map
        .find_power(power)
        .ok_or_else(|| JsError::new(&format!("unknown power {power}")))?;
    let parsed = parse(map, text).map_err(|e| JsError::new(&e.to_string()))?;
    let mut pos = cabal_engine::Position::default();
    let mut place = |kind: UnitKind, region: cabal_engine::Region| {
        let region = if kind == UnitKind::Army {
            cabal_engine::Region::land(region.province)
        } else {
            region
        };
        if pos.unit_at(region.province).is_none() {
            pos.add_unit(cabal_engine::Unit {
                power: p,
                kind,
                region,
            });
        }
    };
    if let (Some(kind), Some(region)) = (parsed.kind, parsed.region) {
        place(kind, region);
    } else if !matches!(parsed.command, cabal_engine::parse::ParsedCommand::Waive) {
        return Err(JsError::new("unit kind is required (A or F)"));
    }
    // units referenced by supports and convoys, so their kind appears in the canonical text
    use cabal_engine::parse::ParsedCommand;
    match parsed.command {
        ParsedCommand::SupportHold {
            target,
            target_kind: Some(k),
        }
        | ParsedCommand::SupportMove {
            target,
            target_kind: Some(k),
            ..
        } => place(k, target),
        ParsedCommand::Convoy { army, .. } => place(UnitKind::Army, army),
        _ => {}
    }
    let err = |e: cabal_engine::parse::ParseError| JsError::new(&e.to_string());
    let out = match phase_kind {
        "M" | "movement" => order_text(map, &pos, &parsed.to_movement(Some(p)).map_err(err)?),
        "R" | "retreat" => retreat_text(map, &pos, &parsed.to_retreat(Some(p)).map_err(err)?),
        "A" | "adjustment" => adjust_text(map, &pos, &parsed.to_adjustment(Some(p)).map_err(err)?),
        other => return Err(JsError::new(&format!("unknown phase kind {other}"))),
    };
    Ok(out)
}

/// What-if preview: adjudicate one movement phase from a state without keeping history.
#[wasm_bindgen]
pub fn preview(
    state: Ts<State>,
    orders: Ts<OrdersByPower>,
    rulebook: Option<String>,
) -> Result<Ts<PhaseOutcome>, JsError> {
    let mut game = Game::from_state(state, rulebook)?;
    game.process(orders)
}

/// BLAKE3 commitment over canonical orders and a hex nonce (a *seal*).
#[wasm_bindgen(js_name = pledgeCommit)]
pub fn pledge_commit(orders: Vec<String>, nonce_hex: &str) -> Result<String, JsError> {
    let nonce = hex::decode(nonce_hex).map_err(|e| JsError::new(&e.to_string()))?;
    Ok(cabal_engine::pledge::commit(&orders, &nonce))
}

/// Does a commitment open with these orders and nonce?
#[wasm_bindgen(js_name = pledgeOpens)]
pub fn pledge_opens(
    commitment: &str,
    orders: Vec<String>,
    nonce_hex: &str,
) -> Result<bool, JsError> {
    let nonce = hex::decode(nonce_hex).map_err(|e| JsError::new(&e.to_string()))?;
    Ok(cabal_engine::pledge::opens(commitment, &orders, &nonce))
}

/// `kept`, `broken` or `void` (a *receipt*).
#[wasm_bindgen(js_name = pledgeReceipt)]
pub fn pledge_receipt(pledged: Vec<String>, submitted: Vec<String>) -> String {
    match cabal_engine::pledge::receipt(&pledged, &submitted) {
        cabal_engine::pledge::Receipt::Kept => "kept",
        cabal_engine::pledge::Receipt::Broken => "broken",
        cabal_engine::pledge::Receipt::Void => "void",
    }
    .to_string()
}
