/**
 * The classic board, generated by tools/mapgen from Natural Earth (public domain).
 * Loaded lazily so the first paint does not wait on 100 KB of geometry.
 */

export type Point = [number, number];

export interface BoardProvince {
  name: string;
  kind: "land" | "coast" | "sea" | "impassable";
  /** SVG path in board units. */
  d: string;
  /** Where a unit stands. */
  unit: Point;
  /** Where the province code is written. */
  label: Point;
  /** Supply centre marker, at the real city. */
  sc?: Point;
  /** Fleet positions on named coasts (`NC`, `SC`, `EC`). */
  coasts?: Record<string, Point>;
}

export interface Board {
  width: number;
  height: number;
  coast: string;
  seaLines: string;
  impassable: string[];
  lakes: string[];
  provinces: Record<string, BoardProvince>;
}

let loading: Promise<Board> | undefined;

export function loadBoard(): Promise<Board> {
  loading ??= import("./board.json").then((m) => m.default as unknown as Board);
  return loading;
}

/** Position of a unit standing on a region such as `PAR` or `STP/NC`. */
export function regionPoint(board: Board, region: string): Point {
  const [code = "", coast] = region.split("/");
  const province = board.provinces[code];
  if (!province) return [0, 0];
  if (coast && province.coasts?.[coast]) return province.coasts[coast];
  return province.unit;
}
